namespace Application
{
    /// <summary>
    /// Defines a contract for cryptographic operations including encryption and decryption of string data.
    /// </summary>
    /// <remarks>
    /// This interface abstracts the cryptographic functionality used throughout the application,
    /// allowing for flexible implementation of different encryption algorithms and strategies.
    /// Implementations should ensure thread-safe operations and consistent encryption/decryption results.
    /// </remarks>
    public interface ICryptoService
    {
        /// <summary>
        /// Encrypts a plaintext string using the configured encryption algorithm.
        /// </summary>
        /// <param name="plainText">The unencrypted text to be encrypted.</param>
        /// <returns>The encrypted string in a format suitable for storage and transmission.</returns>
        /// <remarks>
        /// The encryption implementation should be deterministic to ensure the same plaintext
        /// always produces the same ciphertext, enabling reliable data retrieval and comparison.
        /// </remarks>
        public string EncryptString(string plainText);

        /// <summary>
        /// Decrypts a ciphertext string back to its original plaintext form.
        /// </summary>
        /// <param name="cipherText">The encrypted text to be decrypted.</param>
        /// <returns>The decrypted plaintext string.</returns>
        /// <remarks>
        /// The ciphertext must have been generated by the corresponding EncryptString method
        /// to ensure successful decryption. Invalid or corrupted ciphertext may result in exceptions.
        /// </remarks>
        public string DecryptString(string cipherText);
    }
}