namespace SharedServices
{
using System.Text.Json;

using Application;
using Domain;

/// <summary>
/// Provides functionality for verifying reCAPTCHA tokens by communicating with Google's reCAPTCHA API and evaluating
/// the verification response.
/// </summary>
/// <remarks>Use this service to validate user interactions protected by reCAPTCHA, ensuring that submitted tokens
/// are legitimate and meet the required score threshold. The service depends on application configuration, an HTTP
/// client for API communication, and a response handler for processing verification results. Thread safety is not
/// guaranteed; create separate instances if used concurrently.</remarks>
public class RecaptchaService : IRecaptchaService
{
    private readonly IAppSettingsConfig options;
    private readonly HttpClient httpClient;
    private readonly IResponse response;

    /// <summary>
    /// Initializes a new instance of the <see cref="RecaptchaService"/> class using the specified application settings, HTTP client,.
    /// and response handler.
    /// </summary>
    /// <param name="options">The application settings configuration used to access reCAPTCHA-related options. Cannot be null.</param>
    /// <param name="httpClient">The HTTP client used to send requests to the reCAPTCHA verification endpoint. Cannot be null.</param>
    /// <param name="response">The response handler used to process reCAPTCHA verification responses. Cannot be null.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="options"/>, <paramref name="httpClient"/>, or <paramref name="response"/> is null.</exception>
    public RecaptchaService(IAppSettingsConfig options, HttpClient httpClient, IResponse response)
    {
        this.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        this.response = response ?? throw new ArgumentNullException(nameof(response));
        this.options = options ?? throw new ArgumentNullException(nameof(options));
    }

    /// <summary>
    /// Verifies a reCAPTCHA token by sending a request to Google's reCAPTCHA API and evaluating the response.
    /// </summary>
    /// <param name="token">
    /// The reCAPTCHA token generated by the client-side integration to validate user interaction.
    /// </param>
    /// <param name="action">
    /// The expected action name associated with the reCAPTCHA request, used to ensure the token corresponds to the correct form or interaction.
    /// </param>
    /// <param name="minimumScore">
    /// The minimum acceptable score (between 0 and 1) to consider the reCAPTCHA verification successful. Defaults to 0.5.
    /// </param>
    /// <returns>
    /// An <see cref="IResponse"/> containing:
    /// <list type="bullet">
    /// <item>IsSuccess: <c>true</c> if the reCAPTCHA validation passed and meets the minimum score, otherwise <c>false</c>.</item>
    /// <item>Message: a success or failure message describing the outcome of the verification.</item>
    /// </list>
    /// </returns>
    public async Task<IResponse> VerifyTokenAsync(string token, string action, float minimumScore = 0.5f)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            return this.response.SetFailure(Constants.Token.Provided);
        }

        using (var content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            { "secret", this.options?.Recaptcha?.SecretKey! },
            { "response", token },
        }))
        {
            var response = await this.httpClient.PostAsync(
                "https://www.google.com/recaptcha/api/siteverify",
                content);

            if (!response.IsSuccessStatusCode)
            {
                this.response.IsSuccess = Constants.ResponseFailure;
                this.response.Message = Constants.Token.Captcha.VerificationFailed;
                return this.response;
            }

            var jsonString = await response.Content.ReadAsStringAsync();

            var captchaResponse = JsonSerializer.Deserialize<RecaptchaResponse>(jsonString);

            this.response.IsSuccess = captchaResponse?.Success == true
                && captchaResponse.Action == action
                && captchaResponse.Score >= minimumScore;
        }

        this.response.Message = this.response.IsSuccess
            ? Constants.Token.Captcha.VerficationSuccess
            : Constants.Token.Captcha.VerificationFailed;

        return this.response;
    }
}
}