namespace Infrastructure
{
    using System.Text.Json;
    using System.Text.RegularExpressions;

    using Domain;
    using SharedServices;

    /// <summary>
    /// Specifies the type of audit operation performed, such as creation, update, or deletion.
    /// </summary>
    /// <remarks>Use this enumeration to indicate the nature of an action being audited. The values correspond to
    /// common data modification operations and can be used to categorize audit entries for tracking or reporting
    /// purposes.</remarks>
    public enum AuditMode
    {
        /// <summary>
        /// Indicates that the audit entry represents a creation action.
        /// </summary>
        Create = 0,

        /// <summary>
        /// Represents an update operation in the context of the enumeration.
        /// </summary>
        Update = 1,

        /// <summary>
        /// Specifies the delete operation in the enumeration.
        /// </summary>
        Delete = 2,
    }

    /// <summary>
    /// Provides functionality to interpret audit log data and convert stored audit JSON into human-readable property change
    /// records.
    /// </summary>
    /// <remarks>The AuditInterpreter is designed to process audit entries, typically generated by entity change
    /// tracking, and produce a list of property changes suitable for display in activity logs or audit reports. It uses an
    /// AuditValueResolver to translate property values into readable formats. This class ignores technical fields that are
    /// not relevant to end users and distinguishes between create, update, and delete actions to present changes
    /// appropriately. Instances of AuditInterpreter are not thread-safe; create a new instance for each independent
    /// operation if used concurrently.</remarks>
    public class AuditInterpreter
    {
        // Technical columns not useful to humans
        private static readonly HashSet<string> IgnoredFields =
        [
            "Id",
            "RowVersion",
            "ConcurrencyStamp",
            "ICheckWO2_TStampLong",
            "ICheck_TStampLong"
        ];

        private readonly AuditValueResolver resolver;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditInterpreter"/> class using the specified value resolver.
        /// </summary>
        /// <param name="resolver">The resolver used to interpret and resolve audit values during processing. Cannot be null.</param>
        public AuditInterpreter(AuditValueResolver resolver)
        {
            this.resolver = resolver;
        }

        /// <summary>
        /// Pre-parses and batch-preloads all FK entity display values across multiple log entries to avoid N+1 queries
        /// when resolving details for a page of activity logs.
        /// </summary>
        /// <remarks>Call this method once before calling <see cref="BuildAsync"/> on individual log entries.
        /// All FK entities will be loaded into the cache in batch queries grouped by entity type, so subsequent
        /// <see cref="BuildAsync"/> calls become cache hits with no additional database queries.</remarks>
        /// <param name="logEntries">A sequence of (entityName, changesJson) pairs from the raw activity log records.</param>
        /// <returns>A task representing the asynchronous preload operation.</returns>
        public async Task PreloadBatchAsync(IEnumerable<(string? EntityName, string? ChangesJson)> logEntries)
        {
            // Parse all changes grouped by entity name
            var entriesByEntity = new Dictionary<string, List<AuditEntry>>();

            foreach (var (entityName, changesJson) in logEntries)
            {
                if (string.IsNullOrWhiteSpace(entityName) || string.IsNullOrWhiteSpace(changesJson))
                {
                    continue;
                }

                try
                {
                    var entries = JsonSerializer.Deserialize<List<AuditEntry>>(changesJson);
                    if (entries == null || entries.Count == 0)
                    {
                        continue;
                    }

                    if (!entriesByEntity.TryGetValue(entityName, out var list))
                    {
                        list = [];
                        entriesByEntity[entityName] = list;
                    }

                    list.AddRange(entries);
                }
                catch
                {
                    // Skip invalid JSON
                }
            }

            // Batch-preload all FK entities for each entity type in a single pass
            foreach (var (entityName, entries) in entriesByEntity)
            {
                await this.resolver.PreloadAsync(entityName, entries);
            }
        }

        /// <summary>
        /// Builds a list of activity log change views based on the specified action and audit change data.
        /// </summary>
        /// <remarks>The returned list reflects only relevant changes for the specified action. For create actions,
        /// only new values are shown; for delete actions, only previous values are shown; for update actions, only fields
        /// with changed values are included. If the input JSON is invalid or contains no applicable changes, the method
        /// returns null. Uses <see cref="AuditDisplayAttribute"/> metadata via the resolver for FK and enum display
        /// name resolution, with batch preloading to avoid N+1 queries.</remarks>
        /// <param name="action">The audit action to process. Supported values typically include create, update, and delete operations, which
        /// determine how changes are interpreted.</param>
        /// <param name="changesJson">A JSON string representing a collection of audit entries. Cannot be null, empty, or whitespace. The JSON must be
        /// a valid array of audit entry objects.</param>
        /// <param name="entityName">The CLR type name of the audited entity (e.g. "Organization"). Used to look up
        /// <see cref="AuditDisplayAttribute"/> metadata for FK and enum resolution.</param>
        /// <returns>A list of activity log change views representing the processed changes, or null if no valid changes are found or
        /// if the input is invalid.</returns>
        public async Task<List<ActivityLogChangeView>?> BuildAsync(string action, string? changesJson, string? entityName)
        {
            if (string.IsNullOrWhiteSpace(changesJson))
            {
                return null;
            }

            List<AuditEntry>? entries;

            try
            {
                entries = JsonSerializer.Deserialize<List<AuditEntry>>(changesJson);
            }
            catch
            {
                return null;
            }

            if (entries == null || entries.Count == 0)
            {
                return null;
            }

            // Batch-preload all FK entity display values to avoid N+1 queries
            await this.resolver.PreloadAsync(entityName, entries);

            var results = new List<ActivityLogChangeView>();
            var mode = ResolveMode(action);

            foreach (var entry in entries)
            {
                if (IgnoredFields.Contains(entry.PropertyName))
                {
                    continue;
                }

                var before = await this.resolver.ResolveAsync(entityName, entry.PropertyName, entry.OldValue);
                var after = await this.resolver.ResolveAsync(entityName, entry.PropertyName, entry.NewValue);

                // CREATE → only after values
                if (mode == AuditMode.Create)
                {
                    if (after == "—")
                    {
                        continue;
                    }

                    results.Add(new ActivityLogChangeView
                    {
                        Field = Beautify(entry.PropertyName),
                        Before = "-",
                        After = after,
                    });

                    continue;
                }

                // DELETE → only before values
                if (mode == AuditMode.Delete)
                {
                    if (before == "—")
                    {
                        continue;
                    }

                    results.Add(new ActivityLogChangeView
                    {
                        Field = Beautify(entry.PropertyName),
                        Before = before,
                        After = "-",
                    });

                    continue;
                }

                // UPDATE → show diff only
                if (before == after)
                {
                    continue;
                }

                results.Add(new ActivityLogChangeView
                {
                    Field = Beautify(entry.PropertyName),
                    Before = before,
                    After = after,
                });
            }

            return results.Count == 0 ? null : results;
        }

        /// <summary>
        /// Determines the appropriate audit mode based on the specified action string.
        /// </summary>
        /// <param name="action">The action to resolve to an audit mode. Supported values are "added", "deleted", and "softdeleted"
        /// (case-insensitive). Any other value will be treated as an update.</param>
        /// <returns>The corresponding <see cref="AuditMode"/> value for the specified action. Returns <see cref="AuditMode.Create"/>
        /// for "added", <see cref="AuditMode.Delete"/> for "deleted" or "softdeleted", and <see cref="AuditMode.Update"/>
        /// for all other values.</returns>
        private static AuditMode ResolveMode(string action)
        {
            action = action.ToLowerInvariant();

            return action switch
            {
                "added" => AuditMode.Create,
                "deleted" => AuditMode.Delete,
                "softdeleted" => AuditMode.Delete,
                _ => AuditMode.Update,
            };
        }

        // Convert "AssignedUserId" → "Assigned User"
        private static string Beautify(string property)
            => Regex.Replace(property, "([a-z])([A-Z])", "$1 $2");
    }
}